name: Build/release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Building ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    # if: "contains(github.event.head_commit.message, '#build')"

    strategy:
      matrix:
        include:
          - kind: linux
            os: ubuntu-24.04
            platform: linux
          - kind: windows
            os: windows-latest
            platform: win
          - kind: mac
            os: macos-latest
            platform: osx

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:${{ matrix.platform }} --publish=never

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.platform }}-build
      #     path: |
      #       dist/electron/Packaged/*.exe
      #       dist/electron/Packaged/*.AppImage
      #       dist/electron/Packaged/*.deb
      #       dist/electron/Packaged/*.tar.gz
      #       dist/electron/Packaged/*.dmg
      #       dist/electron/Packaged/*.zip
      #       dist/electron/Packaged/builder-debug.yml

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/electron/Packaged/*.exe
            dist/electron/Packaged/*.AppImage
            dist/electron/Packaged/*.deb
            dist/electron/Packaged/*.tar.gz
            dist/electron/Packaged/*.dmg
            dist/electron/Packaged/*.zip
